version: '2'
services:
    app:
        build: .
        ports:
            - 8080:8080
        links:
            - mongo
    mongo:
        image: mongo:latest
        ports:
            - 27017:27017
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - 1025:1025
            - 8025:8025

